export const jobs: { id: string; title: string; sector: string; city: string; area: string; min: number; max: number; type: string; shift: string; exp: string; education: string; skills: string; benefits: string; duties: string }[] = [];

export const services=[
{icon:'briefcase',name:'Permanent recruitment',tag:'START WITH THE RIGHT FIT',phase:'Core service model',summary:'People who belong on your team, for the long run.',points:['Role brief and salary alignment','Sourcing and skills-based screening','Interview scheduling and feedback','Offer coordination and joining follow-up'],pricing:'Success-based fee agreed before sourcing.',detail:'You employ the selected candidate directly. Agree the fee basis, payment trigger, replacement window and exclusions in a written engagement.'},
{icon:'users',name:'Bulk & frontline hiring',tag:'SCALE WITHOUT THE CHAOS',phase:'Core service model',summary:'One requirement. Multiple roles, locations and joiners.',points:['Location and shift-based sourcing','Batch screening and interview drives','Joining targets and daily funnel reports','No-show tracking and replacement planning'],pricing:'Fixed fee per joined candidate, agreed by volume.',detail:'Ideal for store launches, fulfilment peaks and support teams. Confirm headcount per city, shift, salary, benefits, joining deadline and acceptance criteria.'},
{icon:'clock',name:'Temporary & contract staffing',tag:'FLEX WITH YOUR DEMAND',phase:'Expansion service',summary:'Build a flexible workforce around business demand.',points:['Fixed-term or seasonal workforce planning','Document and onboarding coordination','Attendance inputs and payroll coordination','Associate support and exit formalities'],pricing:'Monthly service fee plus agreed employment costs.',detail:'Employment entity, insurance, statutory responsibilities, supervision and contract terms must be confirmed before deployment.'},
{icon:'wallet',name:'Payroll & compliance support',tag:'EVERY DETAIL ACCOUNTED FOR',phase:'Expansion service',summary:'Bring clarity to the monthly workforce cycle.',points:['Attendance and pay-input reconciliation','Salary breakup and payslip workflow','Statutory checklist and filing coordination','Reimbursements, exceptions and audit records'],pricing:'Per-employee-per-month or scoped retainer.',detail:'Scope includes operational coordination. Applicable PF, ESI, professional tax, minimum wages, overtime and labour requirements need review by a qualified specialist for each location.',href:'https://www.shambhavaa.com/payroll'},
{icon:'layers',name:'RPO & managed hiring',tag:'YOUR RECRUITMENT EXTENSION',phase:'Expansion service',summary:'An embedded hiring process that grows with you.',points:['Dedicated sourcing and screening workflow','Hiring-manager coordination and reporting','Offer-to-joining and retention tracking','Vendor coordination for managed programmes'],pricing:'Project retainer, per-hire fee or blended model.',detail:'Recruitment Process Outsourcing (RPO) covers agreed parts of your hiring process. Managed Service Provider (MSP) programmes can coordinate staffing suppliers, service levels and consolidated reporting.'},
{icon:'zap',name:'Gig & task-based workforce',tag:'PEOPLE FOR THE TASK AT HAND',phase:'Expansion service',summary:'Flexible teams for clearly defined field outcomes.',points:['Merchant onboarding and field operations','Task scope, geography and skills matching','Attendance and task-evidence review','Quality acceptance and payout reconciliation'],pricing:'Per-task or project-based quotation.',detail:'Agree acceptance criteria, proof of completion, safety arrangements, expenses and payment terms before assigning work. Contractor classification requires a fact-specific review.'}
];

export const onboarding=['Approve role, salary and work location','Confirm offer and joining date','Obtain consent for relevant checks','Verify role-specific qualifications','Complete employment agreement','Record payroll inputs through a secure channel','Complete safety and workplace induction','Confirm first-day attendance','Schedule day-7 and day-30 check-ins'];
