export const jobs = [
{id:'warehouse-manager',title:'Warehouse Shift Manager',sector:'Logistics',city:'Delhi NCR',area:'Kapashera Industrial Area',min:25000,max:35000,type:'Full-time',shift:'Day / Night Rotational',exp:'2–4 years',education:'Graduate / Diploma',skills:'Team management, Inventory tracking, WMS software',benefits:'PF, ESI, Health Insurance, Performance Bonus',duties:'Manage a team of 40+ pickers and packers, ensure daily dispatch targets are met, and maintain strict inventory accuracy.'},
{id:'last-mile-delivery',title:'Last-Mile Delivery Partner',sector:'Delivery',city:'Bengaluru',area:'Indiranagar & Koramangala',min:22000,max:35000,type:'Gig / flexible',shift:'Flexible slots',exp:'Fresher or Experienced',education:'10th pass',skills:'Driving, GPS Navigation, Customer communication',benefits:'Weekly payouts, Fuel allowance, Joining bonus',duties:'Deliver grocery and e-commerce packages securely. Must have a valid two-wheeler licence, own vehicle, and a smartphone.'},
{id:'store-manager-apparel',title:'Retail Store Manager',sector:'Retail',city:'Mumbai',area:'Bandra West',min:30000,max:45000,type:'Full-time',shift:'Day shift',exp:'3+ years in retail',education:'Graduate',skills:'Store operations, Visual merchandising, Sales tracking',benefits:'Store discount, PF, ESI, Incentives',duties:'Oversee daily store operations, manage staff rosters, drive sales targets, and ensure high customer satisfaction.'},
{id:'tele-sales-exec',title:'Inside Sales Executive (Financial Services)',sector:'BPO',city:'Hyderabad',area:'Hitec City',min:22000,max:30000,type:'Full-time',shift:'Fixed Day Shift',exp:'1–2 years',education:'12th pass / Graduate',skills:'Fluent Telugu & English, Persuasion, CRM usage',benefits:'Uncapped incentives, Medical insurance',duties:'Call prospective clients to explain personal loan and credit card products, follow up on leads, and close applications.'},
{id:'cnc-operator',title:'CNC Machine Operator',sector:'Manufacturing',city:'Pune',area:'Chakan MIDC',min:20000,max:28000,type:'Full-time',shift:'Rotational shifts',exp:'2+ years',education:'ITI (Machinist / Fitter)',skills:'CNC Programming basics, Quality inspection, Tool setting',benefits:'Subsidised canteen, Transport, PF, ESI',duties:'Operate CNC milling machines, conduct quality checks using micrometres, and maintain daily production logs.'},
{id:'facility-supervisor',title:'Facility Supervisor',sector:'Hospitality',city:'Delhi NCR',area:'Gurugram Sector 44',min:18000,max:24000,type:'Full-time',shift:'Day shift',exp:'1–3 years',education:'12th pass',skills:'Housekeeping management, Vendor coordination, SLA tracking',benefits:'Uniform, Duty meals, PF',duties:'Supervise housekeeping staff across a 4-storey corporate office, ensure hygiene standards, and manage cleaning supplies.'},
{id:'field-merchant-onboarding',title:'Merchant Onboarding Executive',sector:'Sales',city:'Ahmedabad',area:'City-wide',min:20000,max:28000,type:'Full-time',shift:'Day shift',exp:'0–2 years',education:'12th pass',skills:'Gujarati & Hindi, B2B Sales, App installation',benefits:'Travel allowance, Weekly incentives',duties:'Visit retail shops and restaurants to onboard them onto a digital payment platform and install QR codes.'},
{id:'data-entry-operator',title:'Data Entry & Verification Exec',sector:'Operations',city:'Chennai',area:'Guindy',min:16000,max:22000,type:'Full-time',shift:'Day shift',exp:'0–1 year',education:'Graduate',skills:'Typing (35+ WPM), Excel, Document verification',benefits:'PF, ESI, Weekend off',duties:'Verify KYC documents for customer applications, enter data into the internal portal accurately, and flag discrepancies.'}
];
export const services=[
{icon:'briefcase',name:'Permanent recruitment',tag:'START WITH THE RIGHT FIT',phase:'Core service model',summary:'People who belong on your team, for the long run.',points:['Role brief and salary alignment','Sourcing and skills-based screening','Interview scheduling and feedback','Offer coordination and joining follow-up'],pricing:'Success-based fee agreed before sourcing.',detail:'You employ the selected candidate directly. Agree the fee basis, payment trigger, replacement window and exclusions in a written engagement.'},
{icon:'users',name:'Bulk & frontline hiring',tag:'SCALE WITHOUT THE CHAOS',phase:'Core service model',summary:'One requirement. Multiple roles, locations and joiners.',points:['Location and shift-based sourcing','Batch screening and interview drives','Joining targets and daily funnel reports','No-show tracking and replacement planning'],pricing:'Fixed fee per joined candidate, agreed by volume.',detail:'Ideal for store launches, fulfilment peaks and support teams. Confirm headcount per city, shift, salary, benefits, joining deadline and acceptance criteria.'},
{icon:'clock',name:'Temporary & contract staffing',tag:'FLEX WITH YOUR DEMAND',phase:'Expansion service',summary:'Build a flexible workforce around business demand.',points:['Fixed-term or seasonal workforce planning','Document and onboarding coordination','Attendance inputs and payroll coordination','Associate support and exit formalities'],pricing:'Monthly service fee plus agreed employment costs.',detail:'Employment entity, insurance, statutory responsibilities, supervision and contract terms must be confirmed before deployment.'},
{icon:'wallet',name:'Payroll & compliance support',tag:'EVERY DETAIL ACCOUNTED FOR',phase:'Expansion service',summary:'Bring clarity to the monthly workforce cycle.',points:['Attendance and pay-input reconciliation','Salary breakup and payslip workflow','Statutory checklist and filing coordination','Reimbursements, exceptions and audit records'],pricing:'Per-employee-per-month or scoped retainer.',detail:'Scope includes operational coordination. Applicable PF, ESI, professional tax, minimum wages, overtime and labour requirements need review by a qualified specialist for each location.',href:'https://www.shambhavaa.com/payroll'},
{icon:'layers',name:'RPO & managed hiring',tag:'YOUR RECRUITMENT EXTENSION',phase:'Expansion service',summary:'An embedded hiring process that grows with you.',points:['Dedicated sourcing and screening workflow','Hiring-manager coordination and reporting','Offer-to-joining and retention tracking','Vendor coordination for managed programmes'],pricing:'Project retainer, per-hire fee or blended model.',detail:'Recruitment Process Outsourcing (RPO) covers agreed parts of your hiring process. Managed Service Provider (MSP) programmes can coordinate staffing suppliers, service levels and consolidated reporting.'},
{icon:'zap',name:'Gig & task-based workforce',tag:'PEOPLE FOR THE TASK AT HAND',phase:'Expansion service',summary:'Flexible teams for clearly defined field outcomes.',points:['Merchant onboarding and field operations','Task scope, geography and skills matching','Attendance and task-evidence review','Quality acceptance and payout reconciliation'],pricing:'Per-task or project-based quotation.',detail:'Agree acceptance criteria, proof of completion, safety arrangements, expenses and payment terms before assigning work. Contractor classification requires a fact-specific review.'}
];

export const onboarding=['Approve role, salary and work location','Confirm offer and joining date','Obtain consent for relevant checks','Verify role-specific qualifications','Complete employment agreement','Record payroll inputs through a secure channel','Complete safety and workplace induction','Confirm first-day attendance','Schedule day-7 and day-30 check-ins'];
