export const jobs = [
{id:'warehouse-associate',title:'Warehouse Associate',sector:'Logistics',city:'Delhi NCR',area:'Bhiwandi-style fulfilment operations',min:16000,max:22000,type:'Full-time',shift:'Rotational shifts',exp:'Fresher',education:'10th pass',skills:'Picking, packing, barcode scanning',benefits:'Shift allowance, safety equipment',duties:'Pick and pack orders accurately, scan incoming stock and follow warehouse safety procedures.'},
{id:'delivery-executive',title:'Delivery Executive',sector:'Delivery',city:'Bengaluru',area:'Local delivery zones',min:18000,max:30000,type:'Gig / flexible',shift:'Flexible slots',exp:'Fresher',education:'Basic literacy',skills:'Navigation, smartphone use, customer communication',benefits:'Incentives subject to task completion',duties:'Collect and deliver orders in an assigned zone. A valid driving licence and vehicle may be required; confirm expenses and insurance before accepting.'},
{id:'retail-associate',title:'Retail Sales Associate',sector:'Retail',city:'Mumbai',area:'Retail stores',min:18000,max:25000,type:'Full-time',shift:'Day / evening',exp:'0–1 year',education:'12th pass',skills:'Customer service, product knowledge, billing',benefits:'Sales incentives, training',duties:'Help customers find products, support billing and keep the sales floor organised.'},
{id:'customer-support',title:'Customer Support Executive',sector:'BPO',city:'Hyderabad',area:'Customer support centre',min:20000,max:28000,type:'Full-time',shift:'Rotational shifts',exp:'0–1 year',education:'12th pass',skills:'Hindi, English, computer basics',benefits:'Training, shift allowance',duties:'Respond to customer queries by phone or chat, maintain case notes and escalate unresolved issues.'},
{id:'machine-operator',title:'Machine Operator',sector:'Manufacturing',city:'Pune',area:'Industrial belt',min:18000,max:26000,type:'Contract',shift:'Rotational shifts',exp:'1–3 years',education:'ITI / relevant training',skills:'Machine operation, quality checks, safety',benefits:'Safety equipment, shift allowance',duties:'Operate production machinery, check output quality and report maintenance needs to your supervisor.'},
{id:'housekeeping',title:'Housekeeping Associate',sector:'Hospitality',city:'Delhi NCR',area:'Hotels and facilities',min:15000,max:19000,type:'Full-time',shift:'Day / evening',exp:'Fresher',education:'Basic literacy',skills:'Cleaning, hygiene, safe chemical handling',benefits:'Uniform, on-the-job training',duties:'Maintain assigned rooms and common spaces, track supplies and follow hygiene and safety standards.'},
{id:'field-sales',title:'Field Sales Executive',sector:'Sales',city:'Ahmedabad',area:'Assigned city territory',min:18000,max:30000,type:'Full-time',shift:'Day shift',exp:'0–1 year',education:'12th pass',skills:'Local language, relationship building, sales',benefits:'Travel allowance, performance incentives',duties:'Visit prospective customers, explain products and record leads and follow-ups. Confirm travel reimbursement separately.'},
{id:'back-office',title:'Back Office Executive',sector:'Operations',city:'Bengaluru',area:'Office operations',min:17000,max:24000,type:'Full-time',shift:'Day shift',exp:'0–1 year',education:'12th pass',skills:'Data entry, spreadsheets, attention to detail',benefits:'Training, fixed schedule',duties:'Maintain records, verify data accuracy and support daily administrative operations.'}
];
export const services=[
{icon:'briefcase',name:'Permanent recruitment',tag:'START WITH THE RIGHT FIT',phase:'Core service model',summary:'People who belong on your team, for the long run.',points:['Role brief and salary alignment','Sourcing and skills-based screening','Interview scheduling and feedback','Offer coordination and joining follow-up'],pricing:'Success-based fee agreed before sourcing.',detail:'You employ the selected candidate directly. Agree the fee basis, payment trigger, replacement window and exclusions in a written engagement.'},
{icon:'users',name:'Bulk & frontline hiring',tag:'SCALE WITHOUT THE CHAOS',phase:'Core service model',summary:'One requirement. Multiple roles, locations and joiners.',points:['Location and shift-based sourcing','Batch screening and interview drives','Joining targets and daily funnel reports','No-show tracking and replacement planning'],pricing:'Fixed fee per joined candidate, agreed by volume.',detail:'Ideal for store launches, fulfilment peaks and support teams. Confirm headcount per city, shift, salary, benefits, joining deadline and acceptance criteria.'},
{icon:'clock',name:'Temporary & contract staffing',tag:'FLEX WITH YOUR DEMAND',phase:'Expansion service',summary:'Build a flexible workforce around business demand.',points:['Fixed-term or seasonal workforce planning','Document and onboarding coordination','Attendance inputs and payroll coordination','Associate support and exit formalities'],pricing:'Monthly service fee plus agreed employment costs.',detail:'Employment entity, insurance, statutory responsibilities, supervision and contract terms must be confirmed before deployment.'},
{icon:'wallet',name:'Payroll & compliance support',href:'https://shambhavaa.com/payroll',tag:'EVERY DETAIL ACCOUNTED FOR',phase:'Expansion service',summary:'Bring clarity to the monthly workforce cycle.',points:['Attendance and pay-input reconciliation','Salary breakup and payslip workflow','Statutory checklist and filing coordination','Reimbursements, exceptions and audit records'],pricing:'Per-employee-per-month or scoped retainer.',detail:'Scope includes operational coordination. Applicable PF, ESI, professional tax, minimum wages, overtime and labour requirements need review by a qualified specialist for each location.'},
{icon:'layers',name:'RPO & managed hiring',tag:'YOUR RECRUITMENT EXTENSION',phase:'Expansion service',summary:'An embedded hiring process that grows with you.',points:['Dedicated sourcing and screening workflow','Hiring-manager coordination and reporting','Offer-to-joining and retention tracking','Vendor coordination for managed programmes'],pricing:'Project retainer, per-hire fee or blended model.',detail:'Recruitment Process Outsourcing (RPO) covers agreed parts of your hiring process. Managed Service Provider (MSP) programmes can coordinate staffing suppliers, service levels and consolidated reporting.'},
{icon:'zap',name:'Gig & task-based workforce',tag:'PEOPLE FOR THE TASK AT HAND',phase:'Expansion service',summary:'Flexible teams for clearly defined field outcomes.',points:['Merchant onboarding and field operations','Task scope, geography and skills matching','Attendance and task-evidence review','Quality acceptance and payout reconciliation'],pricing:'Per-task or project-based quotation.',detail:'Agree acceptance criteria, proof of completion, safety arrangements, expenses and payment terms before assigning work. Contractor classification requires a fact-specific review.'}
];

export const onboarding=['Approve role, salary and work location','Confirm offer and joining date','Obtain consent for relevant checks','Verify role-specific qualifications','Complete employment agreement','Record payroll inputs through a secure channel','Complete safety and workplace induction','Confirm first-day attendance','Schedule day-7 and day-30 check-ins'];
